apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application }}
  namespace: {{ .Values.namespace }}
stringData:
  {{- if .Values.database }}
  INFLUXDB_DB: {{ .Values.database }}
  {{- end }}
  {{- if .Values.users }}
  {{- if .Values.users.admin }}
  INFLUXDB_ADMIN_USER: {{ .Values.users.admin.name }}
  INFLUXDB_ADMIN_PASSWORD: {{ .Values.users.admin.password }}
  {{- end }}
  {{- if .Values.users.user }}
  INFLUXDB_USER: {{ .Values.users.user.name }}
  INFLUXDB_USER_PASSWORD: {{ .Values.users.user.password }}
  {{- end }}
  {{- end }}