apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.application }}
  ports:
    - name: http
      port: 8086